name: github pages

on:
  push:
    branches:
      - website-redesign

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npx lint-to-the-future output -o lttfOutput --rootUrl guidemaker-ember-template --previous-results https://ember-learn.github.io/guidemaker-ember-template/data.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./lttfOutput
